config/routes.rb
Rails.application.routes.draw do
  mount_roboto
  root to: 'static_pages#top'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :users, only: %i[new create]
  resources :boards do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resource :profile, only: %i[show edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :boards, only: %i[index edit update show destroy]
    resources :users, only: %i[index edit update show destroy]
  end
  get '/sitemap' => redirect('https://s3-ap-northeast-1.amazonaws.com/sitename/sitemap.xml.gz')
end

app/views/shared/_before_login_header.html.erb
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-blue-500 bg-opacity-25">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'don.jpg',size: '70x50' %>
    <% end %>
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to (t 'defaults.login'), login_path ,class: 'nav-link' %>
        </li>
      </ul>
      <a href="https://twitter.com/share?url=https://negative-word-share.com" class="twitter-share-button"
      data-text="みんなでなぐさめ合おう！！"  data-size="large" data-hashtags="Negative_word_share"data-show-count="false"></a>
      <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  </nav>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navigation navbar-light bg-blue-500 bg-opacity-25" >
  <div class="text-center py-10">
    <div class="container-fluid">
        <%=link_to '利用規約', page_path('terms')%>
        <%=link_to 'プライバシーポリシー', page_path('privacy_policy') %>
        <%=link_to 'お問い合わせ', page_path('inquire') %>
      <p class="mt-2">&copy;2022 Negative_word_share</p>
    </div>
  </div>
</nav>

app/views/shared/_header.html.erb
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-blue-500 bg-opacity-25">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'don.jpg', size: '70x50', class: 'rounded-circle mr15'%>
    <% end %>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item dropdown dropdown-slide">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= Board.model_name.human %>
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <%= link_to  t('boards.index.title'), boards_path, class: 'dropdown-item' %>
            <%= link_to  t('boards.new.title'), new_board_path, class: 'dropdown-item' %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to t('boards.bookmarks.title'), bookmarks_boards_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown dropdown-slide">
          <a href="#" class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="header-profile">
            <%= image_tag current_user.avatar_url, size: '40x40', class: 'rounded-circle mr15'%>
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-item"><%= current_user.decorate.full_name %></div>
            <div class="dropdown-divider"></div>
            <%= link_to (t 'profiles.show.title'), profile_path, class: 'dropdown-item' %>
            <%= button_to (t 'defaults.logout'), logout_path,class: 'dropdown-item', method: :delete %>
          </div>
        </li>
        <a href="https://twitter.com/share?url=https://negative-word-share.com" class="twitter-share-button"
        data-text="みんなでなぐさめ合おう！！"  data-size="large" data-hashtags="Negative_word_share"data-show-count="false"></a>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </ul>
    </div>
  </nav>